### PR TITLE
Add awslogs driver and 1.21 API version

### PR DESCRIPTION
**Pull request by samuelkarp**
This supersedes #251, but uses @sfussenegger's commit.

I've updated the go-dockerclient dependency so it now fully supports the 1.21 API version (Docker 1.9).  Unfortunately there are still a few things missing for it to support 1.22 (Docker 1.10), so I have not added that API version.

r? @aaithal @juanrhenals

### CODE REVIEW

**Comment by gregmarr** [comment]
Is this enough to allow us to use log_driver: awslogs in our ECS compose file, or is something more needed?

**Comment by aaithal** [comment]
:shipit:

**Comment by bubenkoff** [comment]
:ship:

**Comment by paulblyth** [comment]
Any ETA on when this will be released and useable?

**Comment by samuelkarp** [comment]
@paulblyth Unfortunately I'm not able to provide an ETA at this time.

**Comment by samuelkarp** [comment]
@paulblyth The `awslogs` driver is supported with our [1.9.0](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.9.0) release.  Please see the [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html) for details on how to use it.

**Comment by gregmarr** [comment]
I set up one of our instances with this logging, and it is logging the docker logs in the group I specified, but there is now also a log group named /var/log/messages with a log stream name equal to the instance ID.  Is this expected?

I had already created the role for these instances with the create log group permission, which is why it was able to create the log group even though the docs say that it won't (with default permissions).

**Comment by gregmarr** [comment]
Before I set this up for the other services for which I already have it running via the cloudwatch agent, Is there any way to change the log stream name?  My current setup uses a service tag combined with the instance ID as the log stream name.  What I need is a way to track down the logs given just the EC2 ID (which I get from haproxy).  The only way that I know of to get the docker container ID is to ssh to the machine, and I don't want to have to do that.

**Comment by gregmarr** [comment]
The docker docks for the awslogs log driver says:
By default, if your Docker daemon is running on an EC2 instance and no region is set, the driver uses the instance’s region.
but ecs-cli compose throws an error if awslogs-region isn't specified in the compose file.

**Comment by samuelkarp** [comment]
@gregmarr 

> there is now also a log group named /var/log/messages with a log stream name equal to the instance ID. Is this expected?

No, it sounds like you might have installed the [CloudWatch Logs agent](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/QuickStartEC2Instance.html), which is separate from the `awslogs` driver.

> I see that there is an awslogs-stream parameter in the docker documentation. Can we use the {instance_id} substitution from the cloudwatch logs agent config file in that parameter?

No, the `awslogs` driver does not support `{instance_id}` substitution.

> The docker docks for the awslogs log driver says:
By default, if your Docker daemon is running on an EC2 instance and no region is set, the driver uses the instance’s region.
but ecs-cli compose throws an error if awslogs-region isn't specified in the compose file.
It also throws an error if awslogs-stream is included.

The Docker documentation is correct for Docker 1.10 and greater.  Docker 1.9 requires `awslogs-region` to be set.

**Comment by gregmarr** [comment]
Thanks.  You're probably right about the agent, I forgot that I had prepared the logs agent setup in the launch configuration setup script, but not deployed it, and then deployed it when I updated the AMI.  I was thinking that enabling awslogs was the only change I made.

Are there any plans to allow the configuration of the log stream name?

**Pull request merged**
