### PR TITLE
Disable Telemetry feature

### PR DESCRIPTION
**Pull request by samuelkarp**
r? @euank @aaithal

### CODE REVIEW

**Comment by aaithal** [comment]
:shipit:

**Comment by samuelkarp** [comment]
Looks like old commits are now failing in Travis too, so something must have changed there: https://travis-ci.org/aws/amazon-ecs-agent/builds/65608101

**Comment by samuelkarp** [comment]
Rebased on #107, now building correctly.  @euank

**Comment by euank** [comment]
:+1:

**Pull request merged**
