### PR TITLE
add awslogs driver and 1.21 api version

### PR DESCRIPTION
**Pull request by sfussenegger**
added the awslogs driver. this required adding the new 1.21 API version

### CODE REVIEW

**Comment by samuelkarp** [comment]
Thanks for taking a look at this!  In order to properly support the 1.21 API, we also need a few changes in the Docker client library we consume (specifically in the `Config` and `HostConfig` structs we use for communication with the Docker daemon).  See https://github.com/fsouza/go-dockerclient/issues/407 for details of the changes we'd need upstream before adding 1.21 API support.

**Comment by sfussenegger** [comment]
I thought it might not be that easy, but since the build was successful I thought I'd give it a try.

The awslogs driver is great stuff though, thanks for implementing. incredible how is it easy to get watch logs from ECS in Amazon Elasticsearch Service.

One thing I noticed while playing around with it in ECS: using the container id as log stream name makes it impossible to tell which streams belongs to which container, at least from the UI. But I assume you guys have bigger plans for logging integration anyway.

**Comment by samuelkarp** [comment]
I'm glad you're finding it useful!  Yeah, I'm aware of the concern with log stream name and that's why it's controllable through `--log-opt awslogs-stream=mystreamname`, but there is some work to make that work nicely for ECS.

**Comment by sfussenegger** [comment]
I think just having name instead of container id would already go a long way. Currently, I don't think there is a way to have a service generate unique stream names other than the default. Thus having some form of variable interpolation would be great, e.g. `--log-opt awslogs-stream=${containerName}`. I believe there is already a ticket for variable interpolation in order to get instance ip injected (`-e PUBLISH_IP=${containerPublicIp}`).

**Comment by sfussenegger** [comment]
Oh, one more thing before I start bothering you. It would be great to have an optional second stream, separating stdout and stderr, e.g. `--log-opt awslogs-err-stream=errors`, e.g. to seperate nginx access logs from server logs. Not sure this is possible with any other logging driver though.

**Comment by samuelkarp** [comment]
Interpolation is one possible way (and yes, #3 talks about some similar use-cases).  The separate stream for stderr is an interesting idea; I don't have time to look at that immediately but if you're interested the source is located [here in the Docker codebase](https://github.com/docker/docker/tree/master/daemon/logger/awslogs).

**Comment by sfussenegger** [comment]
unfortunately I'm no Go programmer - you can see all my previous Go work as part of this PR - but it looks like the [Message](https://github.com/docker/docker/blob/master/daemon/logger/logger.go#L27) struct has a `Source` property that's [supposedly](https://github.com/docker/docker/blob/master/daemon/attach.go#L88) either `"stdout"` or `"stderr"` so there is at least a way to differentiate between the two.

I'll create a PR over at docker for this

**Comment by wr0ngway** [comment]
As far as I can tell, all changes mentioned in fsouza/go-dockerclient#407 that are needed to support 1.21 have been merged in, am I missing something?

**Comment by samuelkarp** [comment]
@wr0ngway Yes, that's correct.  However, we still need to solve the stream name uniqueness concern, since a log stream can only have one writer at a time.

**Comment by wr0ngway** [comment]
Ah ok, I thought that leaving that unset would just default to using the container-id, which would be fine for my use case.  Since its documented that this value needs to be unique, seems like that should be good enough for a release ;)

**Comment by wyaeld** [comment]
@samuelkarp its been several weeks now, are you able to private an update on native aws logging?

**Comment by samuelkarp** [comment]
Closing in favor of https://github.com/aws/amazon-ecs-agent/pull/366.

**Pull request closed without merging**
