### PR TITLE
v1.11.0 release

### PR DESCRIPTION
**Pull request by samuelkarp**
r? @aaithal @kiranmeduri @juanrhenals @richardpen

### CODE REVIEW

**Comment by aaithal** [comment]
:shipit:

**Comment by richardpen** [comment]
👍

**Comment by kevinkarwaski** [comment]
Any idea when v1.11.0 will be officially released? Will that happen as soon as this is merged?

**Comment by samuelkarp** [comment]
@kevinkarwaski We released this today.  We typically keep these pull requests open until we're ready to do a release, at which point they get merged.

**Pull request merged**
