### PR TITLE
feat: conforming envfile parsing to docker compose envfile

### PR DESCRIPTION
**Pull request by rushib1**
### Summary

This pull request aims to support escape characters and support docker-compose [spec](https://docs.docker.com/compose/environment-variables/env-file/) (Doesn't support Parameter expansion)

### Implementation details

I have imported the files from docker compose [reporsitory](https://github.com/compose-spec/compose-go/tree/master/dotenv) and used those files to parse the envfiles

### Testing

New tests cover the changes: 
yes

### Description for the changelog

Feature: Envfile conforming to docker-compose envfile (Not including parameter expansion)

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rushib1** [comment]
This pr is made due to this issue https://github.com/aws/amazon-ecs-agent/issues/3429

**Comment by Realmonia** [comment]
Thanks for the contribution!

**Comment by rushib1** [comment]
1. The docker-compose has the official implementation for their spec, and is not seperated as different pacakge. Since I did not want to import the whole docker-compose package just for the functionality of dotenv, I have imported only the necessary files.    
2. Since it is the official implementation I assumed it to be the only option for the job and haven't explored other functionality.

Let me know if its okay to import the total docker-compose package just for the functionality of dotenv implementation.

**Comment by Realmonia** [comment]
Yep please import the whole package so we can have dependabot to help maintain it.

**Comment by rushib1** [comment]
Hi @Realmonia, whenever I try `go get github.com/compose-spec/compose-go` it keeps updating other dependencies like docker to v24, go-units to v0.5, logrus to v1.9.0 and testify to v1.8.4 any idea what I should do now?

**Comment by Realmonia** [comment]
Hmm interesting. It does not make sense to me as those packages are not part of the dependency in go.mod of the compose-go package. Can you try if handle override of these dependencies to previous version would work? If not, maybe you can try this godotenv dependency https://github.com/joho/godotenv/blob/main/go.mod

**Comment by rushib1** [comment]
Even without the dependency If I try to run the commands `go get` or `go mod download` inside agent folder the dependecies are getting updated.
```
-       github.com/docker/docker v20.10.24+incompatible
+       github.com/docker/docker v24.0.2+incompatible
        github.com/docker/go-connections v0.4.0
-       github.com/docker/go-units v0.4.0
+       github.com/docker/go-units v0.5.0
```

**Comment by Realmonia** [comment]
Oh yeah I forgot that. That makes sense.

**Comment by rushib1** [comment]
Just for your information, these new changes will break the existing spec of task-def
`Each line in an environment file must contain an environment variable in VARIABLE=VALUE format. Spaces or quotation marks are included as part of the values` - [source](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html)

Example case where this will fail:
```
key1="value1
key2=value"
```

**Comment by Realmonia** [comment]
Hey sorry after further discussion with the team, we decide to not make this change for now. As you pointed out this conflicts with the current documentation; we will need our product team to be involved in, and have proper customer wording before we actually make such change. However, it's possible that we will do this in the future, and we will reopen & merge PR then.

Thanks again for the contribution and sorry again for the confusion!

**Pull request closed without merging**
