### PR TITLE
Feature / Nginx Ubuntu

### PR DESCRIPTION
**Pull request by bryantbiggs**
### Summary
- Update Nginx and ubuntu images to latest stable

### Implementation details
- Update Nginx and ubuntu images to latest stable

### Testing

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cyastella** [comment]
updating the target branch for this pull request from [aws:master](https://github.com/aws/amazon-ecs-agent/tree/master) to [aws:dev](https://github.com/aws/amazon-ecs-agent/tree/dev) to point to the working branch =)

**Comment by yunhee-l** [comment]
thank you for resolving the conflict. we will have to merge these PRs one by one, after running set of checks for each PR, so it'll take some time.

**Comment by bryantbiggs** [comment]
no worries at all, thank you!

**Comment by yunhee-l** [comment]
With a number of other PRs this had to keep merge from dev, and seems to be stuck in weird situation where either it complains of conflict or out of sync with dev. Resolving this in favor of https://github.com/aws/amazon-ecs-agent/pull/2522

**Pull request closed without merging**
