### PR TITLE
removing unwanted debug log

### PR DESCRIPTION
**Pull request by sharanyad**
### Summary
This log statement was getting logged almost every second for network modes, which do not have docker network stats.
```
2019-06-04T23:31:36Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:37Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:38Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:39Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:40Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:41Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:42Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:43Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:44Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:45Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:46Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:47Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:48Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:49Z [DEBUG] Network stats not reported for container
2019-06-04T23:31:50Z [DEBUG] Network stats not reported for container
```
Removing it, since its not necessary

### Testing

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yunhee-l** [comment]
on ARM:
--- FAIL: TestHandlerReconnectsOnDiscoverPollEndpointError (0.73s)
	acs_handler_test.go:763: Duration since start is greater than maximum anticipated wait time: 726.597523ms

Retrying arm/unit_test.

**Comment by sharanyad** [comment]
looks like it was fixed - https://github.com/aws/amazon-ecs-agent/pull/1986 , but it fails here

**Comment by sharanyad** [comment]
```
=== RUN   TestHandlerReconnectsOnDiscoverPollEndpointError
2019-06-05T16:07:50Z [ERROR] Error serving to ACS Webserver: <nil>
2019-06-05T16:07:50Z [INFO] ACS Websocket connection closed for a valid reason: <nil>
2019-06-05T16:07:50Z [INFO] Connected to ACS endpoint
2019-06-05T16:07:50Z [ERROR] Error serving to ACS Webserver: EOF
2019-06-05T16:07:50Z [INFO] ACS Websocket connection closed for a valid reason: EOF
2019-06-05T16:07:50Z [INFO] Connected to ACS endpoint
2019-06-05T16:07:50Z [INFO] ACS session context cancelled.
2019-06-05T16:07:50Z [INFO] Reconnecting to ACS in: 275.641803ms
2019-06-05T16:07:50Z [INFO] Interrupted waiting for reconnect delay to elapse; Expect session to close
2019-06-05T16:07:50Z [ERROR] acs: unable to discover poll endpoint, err: oops
2019-06-05T16:07:50Z [INFO] Reconnecting to ACS in: 253.361739ms
2019-06-05T16:07:50Z [INFO] TaskHandler: Stopping periodic container state change submission ticker
2019-06-05T16:07:50Z [INFO] Done waiting; reconnecting to ACS
2019-06-05T16:07:50Z [INFO] Connected to ACS endpoint
2019-06-05T16:07:50Z [INFO] ACS session context cancelled.
2019-06-05T16:07:50Z [INFO] Reconnecting to ACS in: 423.38778ms
2019-06-05T16:07:50Z [INFO] Interrupted waiting for reconnect delay to elapse; Expect session to close
2019-06-05T16:07:50Z [INFO] TaskHandler: Stopping periodic container state change submission ticker
--- FAIL: TestHandlerReconnectsOnDiscoverPollEndpointError (0.52s)
	acs_handler_test.go:763: Duration since start is greater than maximum anticipated wait time: 522.603939ms
```

**Comment by sharanyad** [comment]
```
=== RUN   TestCNIPluginVersionNumber
--- FAIL: TestCNIPluginVersionNumber (0.00s)
	plugin_test.go:454: 
			Error Trace:	plugin_test.go:454
			Error:      	Not equal: 
			            	expected: "2018.10.0"
			            	actual  : "2019.06.0"
			            	
			            	Diff:
			            	--- Expected
			            	+++ Actual
			            	@@ -1 +1 @@
			            	-2018.10.0
			            	+2019.06.0
			Test:       	TestCNIPluginVersionNumber
```

**Comment by sharanyad** [comment]
all the tests passed, merging

**Pull request merged**
