### PR TITLE
engine: Reduce pull status verbosity

### LINKED ISSUE #404: Cannot run amazon-ecs-agent 1.9.0 in debug mode
We have needed debug mode to be able to troubleshoot production issues and it is requested by AWS whenever we report any issues. Unfortunately amazon-ecs-agent 1.9.0 logs insanely in debug mode. Example:

```
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [====================>                              ] 88.01 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [====================>                              ] 88.57 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [====================>                              ] 89.13 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [====================>                              ] 89.69 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [====================>                              ] 90.24 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [====================>                              ]  90.8 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=====================>                             ] 91.36 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=====================>                             ] 91.91 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=====================>                             ] 92.47 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=====================>                             ] 93.03 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=====================>                             ] 93.59 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=====================>                             ] 94.14 MB/216.7 MB
"
2016-05-13T22:46:25Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=====================>                             ]  94.7 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=====================>                             ] 95.26 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [======================>                            ] 95.81 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [======================>                            ] 96.37 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [======================>                            ] 96.93 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [======================>                            ] 97.48 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [======================>                            ] 98.04 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [======================>                            ]  98.6 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [======================>                            ] 99.16 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=======================>                           ] 99.71 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=======================>                           ] 100.3 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=======================>                           ] 100.8 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=======================>                           ] 101.4 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=======================>                           ] 101.9 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=======================>                           ] 102.5 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=======================>                           ] 103.1 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=======================>                           ] 103.6 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [========================>                          ] 104.2 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [========================>                          ] 104.7 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [========================>                          ] 105.3 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [========================>                          ] 105.8 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [========================>                          ] 106.4 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [========================>                          ]   107 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [========================>                          ] 107.5 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [========================>                          ] 108.1 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=========================>                         ] 108.6 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=========================>                         ] 109.2 MB/216.7 MB
"
2016-05-13T22:46:26Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=========================>                         ] 109.7 MB/216.7 MB
"
2016-05-13T22:46:27Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=========================>                         ] 110.3 MB/216.7 MB
"
2016-05-13T22:46:27Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=========================>                         ] 110.9 MB/216.7 MB
"
2016-05-13T22:46:27Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=========================>                         ] 111.4 MB/216.7 MB
"
2016-05-13T22:46:27Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=========================>                         ]   112 MB/216.7 MB
"
2016-05-13T22:46:27Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [=========================>                         ] 112.5 MB/216.7 MB
"
2016-05-13T22:46:27Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [==========================>                        ] 113.1 MB/216.7 MB
"
2016-05-13T22:46:27Z [DEBUG] Pulling image module="TaskEngine" image="censored/censored:censored"Extractingxtracting [==========================>                        ] 113.6 MB/216.7 MB
```

### PR DESCRIPTION
**Pull request by samuelkarp**
Fixes #404

r? @aaithal @juanrhenals @richardpen @pcarrier

### CODE REVIEW

**Comment by pcarrier** [comment]
My gut feeling is that a time-based approach ("at most one line every N ms") would make the logs more predictably useful with a similar amount of code.

**Comment by samuelkarp** [comment]
@pcarrier Thanks for the suggestion!  I think I'd prefer to keep it this way for now as it's very simple, but if this is still too verbose we can look at something like that.

**Comment by samuelkarp** [comment]
@pcarrier I've thought more about what you suggested and I think your suggestion is a better approach.  I've gone ahead and implemented that (and you're right: it's about the same amount of code too).

**Comment by samuelkarp** [comment]
Sample of what this looks like in logs:

```
2016-07-01T05:21:47Z [DEBUG] Pulling image module="TaskEngine" image="xxx" status="Download complete
"
2016-07-01T05:21:49Z [DEBUG] Pulling image module="TaskEngine" image="xxx" status="Extracting [=====================>                             ] 28.41 MB/65.Extracting
"
2016-07-01T05:21:51Z [DEBUG] Pulling image module="TaskEngine" image="xxx" status="Extracting [====================================>              ] 47.35 MB/65.Extracting
"
2016-07-01T05:21:53Z [DEBUG] Pulling image module="TaskEngine" image="xxx" status="Extracting [=============================================>     ]  59.6 MB/65.Extracting
"
2016-07-01T05:21:54Z [DEBUG] Pulling image module="TaskEngine" image="xxx" status="Pull complete
"
```

You can see by looking at the timestamps that the progress bar lines are 2 seconds apart.

**Comment by juanrhenals** [comment]
A unit test would be good, but other than that, LGTM.

**Comment by aaithal** [comment]
lgtm

**Pull request merged**
