### PR TITLE
Merge 'dev' into task-resource branch

### PR DESCRIPTION
**Pull request by sharanyad**
### Summary
same as title

### Testing
- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [x] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yunhee-l** [comment]
I thought there were at least one more change under vendor/ directory after I merged last time, but apparently not.

**Comment by yunhee-l** [comment]
did you exclude this commit on purpose: https://github.com/yunhee-l/amazon-ecs-agent/commit/159ae5c3067e0a0d7387ff68af2a28bc90f3baaa

**Comment by richardpen** [comment]
Can you call out if there are any conflicts during the merge?

**Comment by sharanyad** [comment]
There were merge conflicts in agent/engine/dockeriface/mocks/dockeriface_mocks.go, agent/engine/engine_mocks.go. The volume api mocks are now updated with latest gomock. 
Minor conflicts in api/container.go,  agent/statemanager/state_manager.go and agent/Gopkg.lock, which are fixed.

**Comment by sharanyad** [comment]
> this commit is not pushed to dev, but will be to master: yunhee-l/amazon-ecs-agent@159ae5c how do we include this? would it be pulled in for later merge?

These should be in `dev` once we merge `master` back and we can do a rebase again.

**Pull request merged**
