### PR TITLE
Fixed typo objet -> object

### PR DESCRIPTION
**Pull request by uthark**
Fixed typo objet -> object

### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [x] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes: 

### Licensing

This contribution is under the terms of the Apache 2.0 License: yes

### CODE REVIEW

**Comment by adnxn** [comment]
@uthark thanks! nice catch =] 

do you mind changing the PR to be against `aws:dev`?

**Comment by uthark** [comment]
Could you please clarify?

**Comment by uthark** [comment]
I can rebase it on dev branch.

**Comment by adnxn** [comment]
> Could you please clarify?

I mean, please change the base branch to `aws:dev`.
So at the top it says: uthark  wants to merge 1 commit into `aws:master` from `uthark:patch-1`.
Can you change that to: uthark  wants to merge 1 commit into `aws:dev`  from `uthark:patch-1`?

Thanks.

**Comment by adnxn** [comment]
> I can rebase it on dev branch.
yes please. =]

**Comment by uthark** [comment]
@adnxn Please check again.

**Pull request merged**
