### PR TITLE
Bump agent version to 1.12.1

### PR DESCRIPTION
**Pull request by richardpen**
* Bug - Fixed a bug where agent keeps fetching stats of stopped containers.

r? @samuelkarp @aaithal @juanrhenals

### CODE REVIEW

**Comment by aaithal** [comment]
lgtm. Do we have an understanding of of the failed checks in some of the commits?

**Comment by samuelkarp** [comment]
@aaithal I'm rerunning tests.  I've opened #490 for one that's started to behave flaky, but haven't dug into why yet.  There may be other flaky tests too.

**Comment by aaithal** [comment]
Yeah, just wanted to confirm that it was because of the flaky tests.

**Comment by samuelkarp** [comment]
@aaithal Looks like flaky tests, since they all passed on re-run.

**Comment by samuelkarp** [comment]
:+1:

**Comment by samuelkarp** [comment]
Can you rebase this on top of the current tip of `dev`?

**Comment by aaithal** [comment]
lgtm

**Comment by samuelkarp** [comment]
:+1:

**Pull request merged**
