### PR TITLE
Fix bug where agent is not NACK-ing update messages when updates are disabled

### PR DESCRIPTION
**Pull request by kiranmeduri**
Agent needs to handle and report failure when Update Agent notifications are received and updates are disabled for agent (ECS_UPDATES_ENABLED=false).

r? @samuelkarp @aaithal 

-kiran

### CODE REVIEW

**Comment by aaithal** [comment]
lgtm :shipit:

**Comment by samuelkarp** [comment]
Code looks good, :+1:.

Since we don't have functional tests covering this use-case, can you run this through some manual tests?  Specifically:

* Ensure updates work properly when enabled
* Ensure that the NACK happens properly when updates are disabled

Both will require a bit of manual setup since the agent will report its version as 1.9.0 and there is no greater version available yet.  I think the easiest way to do this will be temporarily changing the version number in your local build.  I can help you with this tomorrow.

**Comment by kiranmeduri** [comment]
# Upgrades Enabled
```
$ curl -s 127.0.0.1:51678/v1/metadata | python -mjson.tool
{
    "Cluster": "...",
    "ContainerInstanceArn": "...",
    "Version": "Amazon ECS Agent - v1.8.2 (*d400f00)"
}

$ sudo yum update -y ecs-init
...
Updated:
  ecs-init.x86_64 0:1.8.2-1.amzn1

Complete!

$ aws ecs update-container-agent --cluster CLUSTER --container-instance CONTAINER_INSTANCE
...
        "agentUpdateStatus": "PENDING",
...
        "versionInfo": {
            "agentVersion": "1.8.2",
            "agentHash": "64205ac",
            "dockerVersion": "DockerVersion: 1.9.1"
        }
    }
}

$ aws ecs describe-container-instances --cluster CLUSTER --container-instance CONTAINER_INSTANCE
...
            "agentUpdateStatus": "UPDATED",
...
            "versionInfo": {
                "agentVersion": "1.9.0",
                "agentHash": "0931217",
                "dockerVersion": "DockerVersion: 1.9.1"
            }
        }
    ]
}

$ curl -s 127.0.0.1:51678/v1/metadata | python -mjson.tool
{
    "Cluster": "...",
    "ContainerInstanceArn": "...",
    "Version": "Amazon ECS Agent - v1.9.0 (0931217)"
}
```
# Updates Disabled

```
2016-05-10T04:41:51Z [DEBUG] Loaded config: Cluster: amiTest, Region: us-west-2, DataDir: /data, Checkpoint: true, AuthType: , UpdatesEnabled: false, DisableMetrics: false, ReservedMem: 0, TaskCleanupWaitDuration: 3h0m0s

$ curl -s 127.0.0.1:51678/v1/metadata | python -mjson.tool
{
    "Cluster": "...",
    "ContainerInstanceArn": "...",
    "Version": "Amazon ECS Agent - v1.8.2 (*d400f00)"
}

$ sudo yum update -y ecs-init

$ aws ecs update-container-agent --cluster CLUSTER --container-instance CONTAINER_INSTANCE
...
        "agentUpdateStatus": "PENDING",
...
        "versionInfo": {
            "agentVersion": "1.8.2",
            "agentHash": "64205ac",
            "dockerVersion": "DockerVersion: 1.9.1"
        }
    }
}

2016-05-10T04:50:08Z [DEBUG] Got a message from websocket module="ws client" ... 
2016-05-10T04:50:08Z [DEBUG] ACS activity occured
2016-05-10T04:50:08Z [WARN] Nacking StageUpdate; reason: Updates are disabled

$ aws ecs describe-container-instances --cluster CLUSTER --container-instance CONTAINER_INSTANCE
...
            "agentUpdateStatus": "FAILED",
...
            "versionInfo": {
                "agentVersion": "1.8.2",
                "agentHash": "d400f00",
                "dockerVersion": "DockerVersion: 1.9.1"
            }
        }
    ]

```

**Comment by samuelkarp** [comment]
It looks like you might have just tested the real 1.8.2 version rather than your changes.  The `yum update ecs-init` command you ran would have reset the sentinel file used by ecs-init to determine whether it had loaded the agent tarball into Docker, so it probably reloaded the tarball.  You can see the evidence of that in your `describe-container-instances` calls, which are showing an `agentHash` of 64205ac.

**Comment by samuelkarp** [comment]
Looks like this needs a rebase as there are merge conflicts, but should be :+1: after fixing the conflicts.

**Pull request closed without merging**
