### PR TITLE
Fix telemetry test for ws2019

### PR DESCRIPTION
**Pull request by suneyz**
### Summary

On WS2019 functional test image mcr.microsoft.com/windows/servercore:ltsc2019,
the behavior to handle path changed from ws2016 image, it needs to set entrypoint with
absolute path or have entrypoint set to powershell to run executable without absolute path.
Also removed unused binary in windows telemetry test.

### Testing

New tests cover the changes:  yes 

* WS2016 succeeded from CI test
* WS2019 output for succeeded tests:
`.\scripts\run-functional-tests.ps1 -BaseImageName mcr.microsoft.com/windows/servercore:ltsc2019`

```
=== RUN   TestTelemetry
--- PASS: TestTelemetry (1091.04s)
utils_windows.go:87: Registry location test_path_1556320072312726900
utils_windows.go:101: datadir C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata941884708\data
utils_windows.go:109: Created directory C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata941884708 to store test data in
utils.go:176: Found agent metadata: {Cluster:ecstest-telemetry-38fe5e81-f41d-465a-94b7-378a3232e7e3 ContainerInstanceArn:0xc0425956e0 Version:Amazon ECS Agent - v1.26.1 (*UNKNOWN)}
utils.go:197: Task definition: ecsftest-windows-telemetry-0185f6c0582d1a65d6f105bfcba31ae3:1
utils.go:217: Started task: arn:aws:ecs:us-west-2:202407901528:task/d647ca2e-163f-4775-a1a3-10b412e6bcb1
utils.go:186: Removing test dir for passed test C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata941884708
=== RUN   TestTelemetryWithStatsPolling
--- PASS: TestTelemetryWithStatsPolling (615.72s)
utils_windows.go:87: Registry location test_path_1556321163179959700
utils_windows.go:101: datadir C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata579929651\data
utils_windows.go:109: Created directory C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata579929651 to store test data in
utils.go:176: Found agent metadata: {Cluster:ecstest-telemetry-polling-98a34289-8b8b-47fe-8831-813ab1862167 ContainerInstanceArn:0xc0422f8050 Version:Amazon ECS Agent - v1.26.1 (*UNKNOWN)}
utils.go:197: Task definition: ecsftest-windows-telemetry-0185f6c0582d1a65d6f105bfcba31ae3:1
utils.go:217: Started task: arn:aws:ecs:us-west-2:202407901528:task/28702166-ef61-4bc9-9d21-982c0cb8d9b3
utils.go:186: Removing test dir for passed test C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata579929651
=== RUN   TestOOMContainer
--- PASS: TestOOMContainer (10.51s)
utils_windows.go:87: Registry location test_path_1556321778875356400
utils_windows.go:101: datadir C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata466057718\data
utils_windows.go:109: Created directory C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata466057718 to store test data in
utils.go:176: Found agent metadata: {Cluster:ecs-functional-tests ContainerInstanceArn:0xc04259c280 Version:Amazon ECS Agent - v1.26.1 (*UNKNOWN)}
utils.go:197: Task definition: ecsftest-oom-container-windows-808d88ffef5545d1e868856c80573e85:1
utils.go:217: Started task: arn:aws:ecs:us-west-2:202407901528:task/b13d1689-3741-4c4f-9b37-dc0f9ab1ae26
utils.go:186: Removing test dir for passed test C:\Users\ADMINI~1\AppData\Local\Temp\ecs_integ_testdata466057718

```

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yunhee-l** [comment]
@suneyz can you update details on how this was tested under the Testing section please?

**Comment by petderek** [comment]
> On WS2019, we need to have entrypoint set to powershell to run executable.

Is this true across the board?

**Comment by suneyz** [comment]
> @suneyz can you update details on how this was tested under the Testing section please?

Updated

**Comment by suneyz** [comment]
> > On WS2019, we need to have entrypoint set to powershell to run executable.
> 
> Is this true across the board?

Interestingly, on ws2016, you don't have to specify powershell, you can run directly from executable as from unmodified file. on ws2019 image for functional test, you have to specify powershell, im not sure what's the reason behind this behavior. 

Another change i made for those tests is to group the exact command together for easy troubleshooting in the future, since it took me a while to figure out exact command that got executed from existing implementation(entrypoint from 1 file and command override from another file).

**Comment by petderek** [comment]
Its not running powershell on 2016, its invoking the binary directly. Invoking it with powershell solves the problem, but just be aware that powershell isn't a prerequisite to having things run. 

What error are you getting? If you specify the absolute path, does it work?

> (entrypoint from 1 file and command override from another file).

A lot of docker containers do this to make 'docker run' easy with flags. I'd prefer to leave this as is. Eg:

`docker run stress --concurrency 1000 --memory 1024`

vs

`docker run --entrypoint C:\stress.exe stress --concurrency 1000 --memory 1024`

**Comment by suneyz** [comment]
> Its not running powershell on 2016, its invoking the binary directly. Invoking it with powershell solves the problem, but just be aware that powershell isn't a prerequisite to having things run.
> 
> What error are you getting? If you specify the absolute path, does it work?
> 
> > (entrypoint from 1 file and command override from another file).
> 
> A lot of docker containers do this to make 'docker run' easy with flags. I'd prefer to leave this as is. Eg:
> 
> `docker run stress --concurrency 1000 --memory 1024`
> 
> vs
> 
> `docker run --entrypoint C:\stress.exe stress --concurrency 1000 --memory 1024`

yeah, you are right. We discussed offline that something changed either in docker or windows functional test image that handles path. Updated the commit message to reflect it is to fix path handle. Setting entrypoint to powershell to be consistent with other windows tests([example](https://github.com/aws/amazon-ecs-agent/blob/master/agent/functional_tests/testdata/taskdefinitions/iam-roles-windows/task-definition.json#L9))


Some context of test working vs not working:


#### working
```
docker run --entrypoint powershell amazon/amazon-ecs-windows-telemetry-test:make  "./stress.exe --concurrency 1000 --memory 1024"

docker run --entrypoint C:\stress.exe amazon/amazon-ecs-windows-telemetry-test:make --concurrency 1000 --memory 1024

docker run amazon/amazon-ecs-windows-telemetry-test:make "C:\stress.exe --concurrency 1000 --memory 1024"
```

#### not working
```
docker run --entrypoint amazon/amazon-ecs-windows-telemetry-test:make  "--concurrency 1000 --memory 1024"

docker run --entrypoint .stress.exe amazon/amazon-ecs-windows-telemetry-test:make  "--concurrency 1000 --memory 1024"

docker run amazon/amazon-ecs-windows-telemetry-test:make  "./stress.exe --concurrency 1000 --memory 1024"


# error message
C:\Program Files\Docker\docker.exe: Error response from daemon: container ff8cff9dbd233a2f0ab3764203da42c47249b66a84b8369643315f2e210f86c6 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":".stress.exe \"--concurrency 1000 --memory 1024\"","WorkingDirectory":"C:\\","CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.
```

**Pull request merged**
