### PR TITLE
Add support for SumoLogic logging driver

### PR DESCRIPTION
**Pull request by bin3377**
### Summary

Add [SumoLogic Docker Logging Driver](https://store.docker.com/plugins/sumologic-logging-plugin) support in docker client

### Implementation details

Add `sumologic` in logging_drivers.go
Add 1.29 as minimum support API version

### Testing

- [x] Builds on Linux (`make release`)
- [ ] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [ ] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [ ] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [ ] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes: 

### Licensing

This contribution is under the terms of the Apache 2.0 License:

### CODE REVIEW

**Comment by samuelkarp** [comment]
Thank you!  I was able to test this and get it working with a task definition like this:

```json
{
        "family": "sumologic-test",
        "containerDefinitions": [
            {
                "name": "hello",
                "image": "ubuntu:latest",
                "cpu": 100,
                "memory": 512,
                "essential": true,
		"entryPoint": ["sh", "-c"],
		"command": ["echo hello sumologic again"],
		"logConfiguration" : {
			"logDriver": "sumologic",
			"options": {
				"sumo-url":"<REDACTED>"
			}
		}
            }
        ]
}
```

Note that I *did* need to install the plugin and specify the `--alias` flag like this: `docker plugin install store/sumologic/docker-logging-driver:1.0.1 --alias sumologic`.

**Comment by rh-lphan** [comment]
Hello,

It is giving me "Run tasks failed: Reasons: ["ATTRIBUTE"] "
is it related to 
https://github.com/aws/amazon-ecs-agent/issues/535

I added this to /etc/ecs/ecs.config and restart
stop ecs 
start ecs
, is it necessary?
ECS_AVAILABLE_LOGGING_DRIVERS='["awslogs","sumo logic"]'

**Comment by bin3377** [comment]
there should be no space between `sumo` and `logic`

**Comment by rh-lphan** [comment]
Even after putting in the above settings, still getting
Run tasks failed
Reasons : ["ATTRIBUTE"]

**Comment by rh-lphan** [comment]
Hello,

I solved the problem with 
/etc/ecs/ecs.config
ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","syslog","sumologic"]

However I see in the ECS agent log:
ime="2017-10-06T04:44:49.789711510Z" level=error msg="Handler for POST /v1.21/containers/create returned error: logger: no log driver named 'sumologic' is registered" 

but I do see
docker plugin ls
ID                  NAME                                          DESCRIPTION                 ENABLED
c935be3e82c7        sumologic:latest                              Sumo Logic logging driver   true

**Comment by jhaynes** [comment]
Hi @rh-lphan,

If you're still running into trouble with the SumoLogic log driver, please feel free to open a new issue here on github with the relevant logs and configuration or engage AWS support directly.

**Pull request merged**
