### PR TITLE
Add Splunk logging driver

### PR DESCRIPTION
**Pull request by mchene**
Updated dockerclient to now support the Splunk docker logging driver.

### CODE REVIEW

**Comment by samuelkarp** [comment]
@mchene Thanks for opening this.  In order for us to accept this change, we'll also need to ensure that the [library we use](https://github.com/fsouza/go-dockerclient) for communicating with Docker fully supports the `Config` and `HostConfig` for the 1.22 API version.  While we can't merge this today, I'll leave this open so we can look after ensuring that 1.22 is fully supported.

**Comment by memory** [comment]
Any ETA for this landing?

**Comment by rupamroy** [comment]
Is there any ETA on when this PR will be merged ?

**Comment by samuelkarp** [comment]
@memory @rupamroy We need support for the 1.22 API `Config` and `HostConfig` in go-dockerclient before we can merge this safely.

**Comment by kevinkarwaski** [comment]
According to like the go-dockerclient README, it supports Docker API up to v1.23. Is that what's needed to land this?

https://github.com/fsouza/go-dockerclient/commit/e199cd2f47624294772a113ee9c469a183256fe1

**Comment by Fathalian** [comment]
Any updates on this ?

**Comment by juanrhenals** [comment]
I have created a new PR (see #441) that merges this change after a rebase on top of the dev branch. The fsouza/go-dockerclient dependency has been updated in the agent(see #439) so this can now be merged safely. Closing this PR.

**Pull request closed without merging**
