### PR TITLE
Replace mongo

### PR DESCRIPTION
**Pull request by shubham2892**
### Summary
Mongo images are replaced with redis and crux images. Using Mongo images were leading to unpredictable results in functional and integration tests everytime Mongo images were updated on docker hub.

### Testing

Integ tests are passing for Arm and Linux. 

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by suneyz** [comment]
integ tests are failing, can you take a look?

**Comment by shubham2892** [comment]
> integ tests are failing, can you take a look?

Taking a look.

**Comment by adnxn** [comment]
i think we can squash commits before merging this yea?

**Comment by shubham2892** [comment]
> i think we can squash commits before merging this yea?

Yes!. Waiting for all the tests to pass, wil squash and merge then. 😄

**Comment by aaithal** [comment]
Why was this pushed when there were unit test failures as well as tests that still haven't completed their execution?

**Comment by shubham2892** [comment]
All the tests did ran and passed. The tests were triggered again on force-push which done to squash the commits. 

The test status were not updated correctly when tests re-ran.

**Comment by aaithal** [comment]
> All the tests did ran and passed. The tests were triggered again on force-push which done to squash the commits.

> The test status were not updated correctly when tests re-ran.


The build status says otherwise. The following tests are currently showing as having a failed status:

```
@amazon-ecs-bot
ecs/arm/integ_test — Failed: Arm integration test suite
@amazon-ecs-bot
ecs/arm/unit_test — Failed: Arm unit test suite
@amazon-ecs-bot
ecs/linux/unit_test — Failed: Linux unit test suite
```

**Pull request merged**
