### PR TITLE
Sig kill timeout

### LINKED ISSUE #126: Tune SIGKILL timeout
I'm assuming ECS just uses the regular 10s default before a SIGKILL, but this is far too low for a number of programs we have which work with queues, any thoughts on making this tuneable?

### PR DESCRIPTION
**Pull request by richardpen**
Resolves #126, Setup Sigkill timeout from environment variable.

r? @samuelkarp @aaithal @juanrhenals

### CODE REVIEW

**Comment by samuelkarp** [comment]
@richardpen It looks like there are merge conflicts here.  Can you resolve those?

**Comment by richardpen** [comment]
@samuelkarp done

**Comment by norcalli** [comment]
+1 I just ran into this using ECS for managing long running worker jobs at my company. Would appreciate this feature.

**Comment by amvapor** [comment]
+1 for this as well, README should probably get updated as well to list the new configuration variable.

**Comment by samuelkarp** [comment]
:+1:

**Comment by aaithal** [comment]
lgtm. Can you add an integ test as well?

**Comment by richardpen** [comment]
Added Integration test for the SIGKILL timeout

r? @samuelkarp @aaithal @juanrhenals

**Comment by aaithal** [comment]
:shipit:

**Comment by samuelkarp** [comment]
:+1:

**Comment by azylman** [comment]
Super exciting that this got merged! Is there a time frame for making a new release of the agent with this feature?

**Comment by chenliu0831** [comment]
👍

**Pull request merged**
