### PR TITLE
Merging AgentMetrics branch into dev

### PR DESCRIPTION
**Pull request by yunhee-l**
### Summary
Merging AgentMetrics branch into dev

### Implementation details
dev branch has been rebased into AgentMetrics branch. 

### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [x] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes: Yes

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by petderek** [comment]
Did you have to make any additional changes?

**Comment by yunhee-l** [comment]
this is what Kar had left, as-is.

**Comment by pecigonzalo** [comment]
Is there a document of the exposed metrics?

**Comment by pecigonzalo** [comment]
Sorry to @ you guys, but this questions has been open for a while. @petderek @yunhee-l @yumex93

**Comment by yunhee-l** [comment]
> Is there a document of the exposed metrics?

Hi @pecigonzalo, 
This is not a feature that's been designed as customer facing, and hence there are no public documents on exposed metrics.

**Pull request merged**
