### PR TITLE
vendor: Update go-dockerclient

### PR DESCRIPTION
**Pull request by vsiddharth**
Signed-off-by: Vinothkumar Siddharth <sidvin@amazon.com>

### Summary

Update vendored go-dockerclient

### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [ ] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [ ] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes:  No

### Licensing

This contribution is under the terms of the Apache 2.0 License:  YES

### CODE REVIEW

**Comment by aaithal** [comment]
@vsiddharth can you take a look at the failing test(s) ?

**Comment by vsiddharth** [comment]
#922 seems to have gone away with this change. However I'm double checking the other failures

**Comment by vsiddharth** [comment]
This can be against `dev` but I'll need to pull these changes onto `task-cgroup` for some work.
Would be rather I base this against `dev` ?

**Comment by aaithal** [comment]
Yeah, I think we need to re-vendor this for other things being worked on as well. Let's just do this against dev and you can rebase this branch from that.

**Comment by vsiddharth** [comment]
Cool, I'll update the branches

**Comment by vsiddharth** [comment]
@aaithal I've changed the base branches but the CI systems are behaving strangely since. 

* https://ci.appveyor.com/project/vsiddharth/amazon-ecs-agent/build/122
* https://travis-ci.org/vsiddharth/amazon-ecs-agent/builds/270598340

Would you rather I open a new PR ?

**Comment by aaithal** [comment]
@vsiddharth as long as they succeed, it's fine. Please update the PR when other tests have passed as well (the ones not checked in PR description)

**Comment by samuelkarp** [comment]
Close/reopen to trigger Travis and AppVeyor.

**Comment by samuelkarp** [comment]
@vsiddharth Can you update the status here about integration tests on Linux and functional tests on Windows?

**Comment by vsiddharth** [comment]
@samuelkarp The `ImageCleanup` tests were failing on this branch last time I checked.

**Comment by samuelkarp** [comment]
@vsiddharth Are you planning on addressing those failures?  We shouldn't merge this until all the tests are passing.

**Comment by samuelkarp** [comment]
@vsiddharth Ping...

**Comment by vsiddharth** [comment]
@samuelkarp I haven't had the time to investigate the failures. I can look into the test failures later.

**Comment by richardpen** [comment]
Replaced with #987

**Pull request closed without merging**
