### PR TITLE
allow setting of Docker NetworkMode

### LINKED ISSUE #185: --net=host support
Dockers default behavior is to give a container a private network stack and to build a bridge with the host's network interface. This has considerable performance drawbacks (see netperf in [here](http://blogs.vmware.com/performance/2014/10/docker-containers-performance-vmware-vsphere.html) ) and is an absolute nogo for some types of applications (including mine). Is host-native interface (--net=host) supported or will it ever be supported?

Copied from: https://forums.aws.amazon.com/thread.jspa?threadID=177850&tstart=25

There are a couple of forks out there that attempt to provide support, for example: https://github.com/chaos-generator/amazon-ecs-agent

But it would be great if there were official support for this in the AWS repo.  Not having this really precludes ECS from performance sensitive applications.

### PR DESCRIPTION
**Pull request by bobzoller**
fixes #185.

`echo ECS_DOCKER_NETWORKMODE=host >> /etc/ecs/ecs.config`

Best I can tell the relevant tests are passing, but I'd appreciate a little guidance on how to test this on my live boxes.  When I run my own agent docker image that was built with `make release`, I ultimately get the following cert error in my logs:

```
2016-05-17T02:12:06Z [ERROR] Could not register module="api client" err="RequestError: send request failed
caused by: Post https://ecs.us-east-1.amazonaws.com/: x509: certificate signed by unknown authority"
```

### CODE REVIEW

**Comment by aaithal** [comment]
Hi @bobzoller,
 
Thanks for opening this pull request! Unfortunately, we won't be able to accept this change, as we believe it will lead to incorrect behavior and cause confusion when launching tasks due to the concerns listed below:
 
* Instead of a global change at the agent level, network mode is really a property of a container and would make more sense to be part of the container definition in the task definition
* Furthermore, the ECS scheduler tracks ports as resources in the Container Instance and an environment variable controlling containers' network stack makes it harder for this to be tracked
 
However, we do believe that the following set of changes would solve this problem in a more generic way in the ECS Agent:
 
* Expose a `networkMode` field in the Task Definition (An example of accepted values here could: `bridge`, `host` and `none`)
* Pass the `networkMode`to the ECS Agent from ECS backend based on Task's parameters and use this field in the ECS Agent to set `--net=host` if needed
 
Please let us know if that helps in addressing your use-case. We are also interested in learning about your use-case for different NetworkMode settings as that would help us prioritize.

Thanks,
Anirudh

**Comment by bobzoller** [comment]
yes that sounds great.  my use case is simply squeezing as much performance
out of docker networking as possible.  my understanding (though I don't
have numbers) is that I'll get some non-negligible gain by switching from
bridge to host networking.  since I trust my workloads to behave well, this
seems like an easy win.

**Comment by bobzoller** [comment]
I assume since this now involves changes to the TaskDefinition, my help on
an agent PR won't be very valuable or help this get released quickly.
Happy to help if it makes sense though.

**Comment by aaithal** [comment]
@bobzoller Thanks again for the pull request. I'm closing this for now. We'll update #185 when we have an update.

**Pull request closed without merging**
