### PR TITLE
Feature / Busybox

### PR DESCRIPTION
**Pull request by bryantbiggs**
### Summary
- Update busybox image versions to latest stable version

### Implementation details
- Update busybox image versions to latest stable version

### Testing

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cyastella** [comment]
hey @bryantbiggs, thanks for sending this out! Just to better understand this, what's the motivation behind bumping the image to `1.32.0`? Was there any problem with `1.29.*`?

**Comment by bryantbiggs** [comment]
hello @cyastella - no issues with the current other than bumping the version to take advantage of the latest bug fixes, improvements, and any security updates

**Comment by cyastella** [comment]
> hello @cyastella - no issues with the current other than bumping the version to take advantage of the latest bug fixes, improvements, and any security updates

Thanks for the explanation!! Super helpful! I'm just going to check if there would be any side effect or potential impact before we decide whether to merge this =)

**Comment by bryantbiggs** [comment]
no worries! the same goes with the other pull requests - I thought it made more sense to split them up but same reasoning: update to latest stable versions for bug fixes, security enhancements, etc.

**Comment by cyastella** [comment]
updating the target branch for this pull request from [`aws:master`](https://github.com/aws/amazon-ecs-agent/tree/master) to [`aws:dev`](https://github.com/aws/amazon-ecs-agent/tree/dev) to point to the working branch =)

**Pull request merged**
