### PR TITLE
Add Prometheus port number to reserved ports

### PR DESCRIPTION
**Pull request by sharanyad**
### Summary
fixing README for https://github.com/aws/amazon-ecs-agent/issues/1814

### Testing

- [ ] Builds on Linux (`make release`)
- [ ] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [ ] Unit tests on Linux (`make test`) pass
- [ ] Unit tests on Windows (`go test -timeout=30s ./agent/...`) pass
- [ ] Integration tests on Linux (`make run-integ-tests`) pass
- [ ] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [ ] Functional tests on Linux (`make run-functional-tests`) pass
- [ ] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yunhee-l** [comment]
does it matter that if ECS_ENABLE_PROMETHEUS_METRICS is set to false, we are technically not going to "reserve" port 51680?

**Comment by sharanyad** [comment]
ah missed that flag. It's true that the port won't be reserved. But if ECS_ENABLE_PROMETHEUS_METRICS  is set to true, it will be reserved silently. What would you suggest doing here?

**Comment by yunhee-l** [comment]
Prometheus metrics is probably a feature that majority of our customers won't be using for their day to day workload. Can we loop in doc writers and get their opinion on this?

**Comment by petderek** [comment]
>reserved silently

 Does agent communicate this to the scheduler?

**Comment by adnxn** [comment]
adding to @yunhee-l concerns - do we document what each of these ports are reserved for anywhere?

**Comment by sharanyad** [comment]
> do we document what each of these ports are reserved for anywhere?

yes -- https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html

**Comment by sharanyad** [comment]
> Does agent communicate this to the scheduler?

@petderek  no, agent does not communicate reserved ports to backend

**Comment by samuelkarp** [comment]
> @petderek no, agent does not communicate reserved ports to backend

@sharanyad Reserved ports should be communicated as part of RegisterContainerInstance

**Comment by yunhee-l** [comment]
we are not releasing prometheus as customer feature (see https://github.com/aws/amazon-ecs-agent/pull/1834), and we are not likely to enable this in our releases. Do we still need to reserve these ports?

**Comment by samuelkarp** [comment]
> we are not releasing prometheus as customer feature (see #1834), and we are not likely to enable this in our releases. Do we still need to reserve these ports?

If the feature is enabled (including through the use of an environment variable) I would recommend reserving the ports.

**Comment by sharanyad** [comment]
looks like it's already added 
see : https://github.com/aws/amazon-ecs-agent/issues/1843

**Comment by hflamboauto1** [comment]
@sharanyad  I don't see this on master https://github.com/aws/amazon-ecs-agent/README.md
I see https://github.com/aws/amazon-ecs-agent/issues/1814

**Pull request closed without merging**
