### PR TITLE
chore: pkg imported more than once

### PR DESCRIPTION
**Pull request by testwill**
### Summary

 package "github.com/aws/amazon-ecs-agent/ecs-agent/logger/audit" is being imported more than once
### Testing

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by danehlim** [comment]
Thank you for your contribution, we will take a look at the proposed changes.

**Review by amogh09 — DISMISSED** [review]
Thank you!

**Review by danehlim — DISMISSED** [review]

**Comment by danehlim** [comment]
Hi @testwill, could you please update your pull request such that the corresponding vendored file in the agent module at `agent/vendor/github.com/aws/amazon-ecs-agent/ecs-agent/tmds/handlers/v1/credentials_handler.go` ([link here]( https://github.com/aws/amazon-ecs-agent/blob/master/agent/vendor/github.com/aws/amazon-ecs-agent/ecs-agent/tmds/handlers/v1/credentials_handler.go)) also no longer has the duplicate import? You should be able to this by simply going into the agent directory and running `go mod tidy` and `go mod vendor`.

Thank you once again for catching this duplicate import!

**Comment by testwill** [comment]
@danehlim ok

**Review by danehlim — APPROVED** [review]

**Review by amogh09 — APPROVED** [review]

**Pull request merged**
