### PR TITLE
readme: Update installation instructions

### PR DESCRIPTION
**Pull request by samuelkarp**
### Summary
Updates the installation instructions in the README to be in sync with [our documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html).  This should help address some confusion (like in https://github.com/aws/amazon-ecs-agent/issues/511).

### Implementation details
No implementation.

### Testing
Followed these instructions on an Ubuntu 14.04 instance.

### Description for the changelog
No changelog description

### Licensing
This contribution is under the terms of the Apache 2.0 License: yes (Amazon employee)

r? @aaithal @nrdlngr

### CODE REVIEW

**Comment by jamesongithub** [comment]
maybe a ref to the docs, so don't have to worry about keeping them in sync

**Comment by samuelkarp** [comment]
@jamesongithub There's one right below the "Usage" header, but I think it's helpful to have it here as well.

**Comment by aaithal** [comment]
:shipit:

**Comment by rafaelmagu** [comment]
These instructions did not give me a working endpoint inside the container until I accepted all traffic from `docker0` with something similar to:
```
iptables -A INPUT -i docker0 -j ACCEPT
```

**Comment by samuelkarp** [comment]
@rafaelmagu That's interesting; can you share more about what system you're running on?  The instructions here are the same ones we use [in `ecs-init`](https://github.com/aws/amazon-ecs-init/blob/v1.12.1-1/ecs-init/exec/iptables/iptables.go#L110-L130) for the ECS-optimized AMI.

**Comment by rafaelmagu** [comment]
We are rolling our own Ubuntu 14.04 AMIs. We have existing iptables rules in place, hence why it got me confused.

We ran this (but with `-I`) to add the exception right before our `REJECT` rule.
```
iptables -A INPUT -i docker0 -p tcp -m tcp --dport 51679 -j ACCEPT
```

**Comment by samuelkarp** [comment]
Are the existing iptables rules (the `REJECT` rule) ones you put in place or ones that were otherwise installed on the hosts?  I've used these instructions with the Ubuntu 14.04 AMI in the AWS Marketplace successfully.

**Comment by rafaelmagu** [comment]
@samuelkarp we put those in place as part of our hardening. Can I suggest the documentation be appended to explain what these rules actually do?

**Comment by jamesongithub** [comment]
we're on ubuntu 14.04 also , didn't need to change iptables other than the ones in the docs

**Pull request merged**
