### PR TITLE
Fix code generation error for acs/tcs api

### PR DESCRIPTION
**Pull request by richardpen**
### Summary

Fix issue #812 
### Implementation details

The [aws-sdk-go](https://github.com/aws/aws-sdk-go/blob/63041ae9ee94e32d0f2927f3cbc61f7ccea9b131/private/model/api/api.go#L191) ignore the `errors` type when generating the code. Implement a method that return all the shapes with error types to generate all the structure including the `errors` type.

### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [x] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass
- [x] `make gogenerate`

### Licensing

This contribution is under the terms of the Apache 2.0 License: 
yes

### CODE REVIEW

**Comment by petderek** [comment]
@jahkeup what is the change specifically?

**Comment by jahkeup** [comment]
I have minor changes to the generated packages in my checkout after running (eg: import names, copyright date).

**Comment by petderek** [comment]
Naming for some `ecr` imports isn't deterministic. I've seen this when running make gogenerate -- I'm not sure fixing that should be part of this CR.

**Comment by jahkeup** [comment]
@petderek that's a bit annoying, thanks for clarifying for me! Let's chat offline about if/how we could fix that for the future.

**Pull request merged**
