### PR TITLE
Update build tools for 8 char short sha

### PR DESCRIPTION
**Pull request by jahkeup**
### Summary

Use 8 character sha in publishing common for scripts.

### Implementation details
I changed `--short` to `--short=8`.

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jhaynes** [comment]
@aaithal Should we pin https://github.com/aws/amazon-ecs-agent/blob/master/Makefile#L215 to 8 chars also?

**Comment by aaithal** [comment]
can't think of a reason not to do that. would also make sense to apply the same change here as well: https://github.com/aws/amazon-ecs-cni-plugins/blob/0c6216c60401232805e50e31d4040ae84b0b23cf/Makefile#L14

**Comment by jahkeup** [comment]
As long as there are no assumptions for the CNI plugins in this or its own package I'd be happy to have this consistently applied everywhere.

**Comment by jahkeup** [comment]
PTAL, there's one more `--short` that was updated.

**Pull request merged**
