### PR TITLE
Fix gmsa config

### PR DESCRIPTION
**Pull request by vsiddharth**
Signed-off-by: Vinothkumar Siddharth <sidvin@amazon.com>

### Summary

Fix the config that prevented the environment override from disabling the feature. 

### Testing

New tests cover the changes: 
Yes

### Description for the changelog

Bug - Resolved disabling gMSA feature using environment overrides

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yumex93** [comment]
How does your pr fix the bug? What is doing here is just changing the default config to **false**, however, the env var should take precedence over default config, so theoretically, if the env var is set, it would take the env var value. Did you test that based on your current change, if you set env var to **true** , does the value get read correctly?

**Comment by vsiddharth** [comment]
> How does your pr fix the bug? What is doing here is just changing the default config to **false**, however, the env var should take precedence over default config, so theoretically, if the env var is set, it would take the env var value. Did you test that based on your current change, if you set env var to **true** , does the value get read correctly?

The changes were tested by both @somujay and myself. 

In Golang, the default for bool type is `false`. 

If the env variable is set to false, the feature will be disabled. 
If the env variable is set to true, additional checks will be performed before enabling the feature.

**Comment by yumex93** [comment]
> > How does your pr fix the bug? What is doing here is just changing the default config to **false**, however, the env var should take precedence over default config, so theoretically, if the env var is set, it would take the env var value. Did you test that based on your current change, if you set env var to **true** , does the value get read correctly?
> 
> The changes were tested by both @somujay and myself.
> 
> In Golang, the default for bool type is `false`.
> 
> If the env variable is set to false, the feature will be disabled.
> If the env variable is set to true, additional checks will be performed before enabling the feature.

How the Golang default bool value affect the situation here?  Which code snippet gets affected? Can I get more details?

**Comment by vsiddharth** [comment]
> > > How does your pr fix the bug? What is doing here is just changing the default config to **false**, however, the env var should take precedence over default config, so theoretically, if the env var is set, it would take the env var value. Did you test that based on your current change, if you set env var to **true** , does the value get read correctly?
> > 
> > 
> > The changes were tested by both @somujay and myself.
> > In Golang, the default for bool type is `false`.
> > If the env variable is set to false, the feature will be disabled.
> > If the env variable is set to true, additional checks will be performed before enabling the feature.
> 
> How the Golang default bool value affect the situation here? Which code snippet gets affected? Can I get more details? Thanks.

Please let me know what details you require. 

This issue surfaced when `environmentConfig` and `defaultConfig` are merged for the final config.

**Pull request closed without merging**
