### PR TITLE
Move agent logger to ecs-agent module

### PR DESCRIPTION
**Pull request by danehlim**
### Summary

Move agent logger to ecs-agent module and refactor accordingly. This allows us to use the logger for logging in the ecs-agent module without introducing a dependency cycle in which the ecs-agent module depends on agent module while the agent module already depends on ecs-agent module.

For context on why we prefer to use the current agent logger over seelog directly, please refer to the original pull request for this functionality: https://github.com/aws/amazon-ecs-agent/pull/2709

### Implementation details

1. Move below agent logger files to ecs-agent module
   - `agent/logger/buffer_pool.go` -> `ecs-agent/logger/buffer_pool.go`
   - `agent/logger/buffer_pool_test.go` -> `ecs-agent/logger/buffer_pool_test.go`
   - `agent/logger/eventlog_windows.go` -> `ecs-agent/logger/eventlog_windows.go`
   - `agent/logger/field/constants.go` -> `ecs-agent/logger/field/constants.go` 
   - `agent/logger/format.go` -> `ecs-agent/logger/format.go` 
   - `agent/logger/format_test.go` -> `ecs-logger/format_test.go`
   - `agent/logger/generate_mocks.go` -> `ecs-agent/logger/generate_mocks.go`
   - `agent/logger/global.go` -> `ecs-agent/logger/global.go`
   - `agent/logger/global_test.go` -> `ecs-agent/logger/global_test.go`
   - `agent/logger/log.go` -> `ecs-agent/logger/log.go`
   - `agent/logger/log_init_test.go` -> `ecs-agent/logger/log_init_test.go`
   - `agent/logger/log_test.go` -> `ecs-agent/logger/log_test.go`
   - `agent/logger/log_unix_test.go` -> `ecs-agent/logger/log_unix_test.go`
   - `agent/logger/log_windows_test.go` -> `ecs-agent/logger/log_windows_test.go`
   - `agent/logger/mocks/logger_mocks.go` -> `ecs-agent/logger/mocks/logger_mocks.go`
   - `agent/logger/platform_unix.go` -> `ecs-agent/logger/platform_unix.go`
   - `agent/logger/runtime_stats_logger.go` -> `ecs-agent/logger/runtime_stats_logger.go`
   - `agent/logger/structured_logger.go` -> `ecs-agent/logger/structured_logger.go`
   - `agent/logger/structured_logger_test.go` -> `ecs-agent/logger/structured_logger_test.go`
2. Update imports accordingly based off of above implementation detail
3. Refactor `StartRuntimeStatsLogger()` function in `ecs-agent/logger/runtime_stats_logger.go` to just take in runtime stats log file path as a parameter instead of the entire agent config (since that is the only necessary information)
   - Update `agent/app/run.go` to pass in runtime stats log file to `logger.StartRuntimeStatsLogger()` function instead of entire agent config
4. Improve logging in existing ecs-agent module files `ecs-agent/doctor/doctor.go` and `ecs-agent/tmds/logging/logging_handler.go` by using `github.com/aws/amazon-ecs-agent/ecs-agent/logger` instead of `github.com/cihub/seelog` directly
5. Run `go mod tidy` and `go mod vendor` in `agent/` and `ecs-agent/` directories

### Testing

Unit, integration, and functional tests.

Manually verified that log statements that were modified as part of the refactor continue to appear.
Example:
```
1683570112824228823 [Debug] logger=structured msg="Ran instance health check" instanceHealthcheckType="Agent" instanceHealthCheckResult=OK
1683570112824266843 [Debug] logger=structured msg="Ran instance health check" instanceHealthcheckType="Agent" instanceHealthCheckResult=IMPAIRED
```

### Description for the changelog

Move agent logger to ecs-agent module

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sparrc** [comment]
This log you put in the overview looks different to me:

```
1683570112824228823 [Debug] logger=structured msg="Ran instance health check" instanceHealthcheckType="Agent" instanceHealthCheckResult=OK
1683570112824266843 [Debug] logger=structured msg="Ran instance health check" instanceHealthcheckType="Agent" instanceHealthCheckResult=IMPAIRED
```

previously wouldn't this have started with:

`level=debug time=2023-05-04T22:20:12Z`

**Comment by sparrc** [comment]
also why has this caused so many changes in the vendor directory? is dev branch not up to date?

**Comment by danehlim** [comment]
> This log you put in the overview looks different to me:
> 
> ```
> 1683570112824228823 [Debug] logger=structured msg="Ran instance health check" instanceHealthcheckType="Agent" instanceHealthCheckResult=OK
> 1683570112824266843 [Debug] logger=structured msg="Ran instance health check" instanceHealthcheckType="Agent" instanceHealthCheckResult=IMPAIRED
> ```
> 
> previously wouldn't this have started with:
> 
> `level=debug time=2023-05-04T22:20:12Z`

I got the example logs from the output of `make test`. In this case, wouldn't we expect to see `[Debug] logger=structured` instead of `level=debug` at the start of the statement, since we switched from using `seelogf.Debug()` to `logger.Debug()` for the functionality tested in this associated test case?



> also why has this caused so many changes in the vendor directory? is dev branch not up to date?

I believe dev branch is up to date - running `go mod tidy` and `go mod vendor` on current dev branch does not result in any changes. 

Changes in `agent/vendor` all seem to be the result of changes made to the ecs-agent module in this PR, as agent module is dependent on ecs-agent module. Changes in `ecs-agent/vendor` are the result of new imports introduced by the files that are new to ecs-agent module in this PR. Are there any specific changes in either of the vendor directories here that are unexpected to you?

**Comment by danehlim** [comment]
@sparrc
> This log you put in the overview looks different to me:
> 
> ```
> 1683570112824228823 [Debug] logger=structured msg="Ran instance health check" instanceHealthcheckType="Agent" instanceHealthCheckResult=OK
> 1683570112824266843 [Debug] logger=structured msg="Ran instance health check" instanceHealthcheckType="Agent" instanceHealthCheckResult=IMPAIRED
> ```
> 
> previously wouldn't this have started with:
> 
> `level=debug time=2023-05-04T22:20:12Z`

I got the example logs from the output of `make test`. In this case, wouldn't we expect to see `[Debug] logger=structured` instead of `level=debug` at the start of the statement, since we switched from using `seelogf.Debug()` to `logger.Debug()` for the functionality tested in this associated test case?



> also why has this caused so many changes in the vendor directory? is dev branch not up to date?

I believe dev branch is up to date - running `go mod tidy` and `go mod vendor` on current dev branch does not result in any changes. 

Changes in `agent/vendor` all seem to be the result of changes made to the ecs-agent module in this PR, as agent module is dependent on ecs-agent module. Changes in `ecs-agent/vendor` are the result of new imports introduced by the files that are new to ecs-agent module in this PR. Are there any specific changes in either of the vendor directories here that are unexpected to you?

**Comment by sparrc** [comment]
> In terms of this PR, changes in agent/vendor all seem to be the result of changes made to the ecs-agent module in this PR, as agent module is dependent on ecs-agent module. Changes in ecs-agent/vendor are the result of new imports introduced by the files that are new to ecs-agent module in this PR. Are there any specific changes in either of the vendor directories here that are unexpected to you?

did you run `go mod tidy` in both the `agent/` and `ecs-agent/` directories? (ie, can we delete anything from agent/ directory after this change?)

**Comment by danehlim** [comment]
@sparrc 
> did you run `go mod tidy` in both the `agent/` and `ecs-agent/` directories? (ie, can we delete anything from agent/ directory after this change?)

That's right, I ran `go mod tidy` in both `agent/` and `ecs-agent/` directories after making the changes. If we could remove anything from `agent/vendor` after this change, running `go mod tidy` and `go mod vendor` in `agent/` would have detected that and clean up any files that could be removed accordingly IIUC.

**Review by sparrc — APPROVED** [review]

**Review by SreeeS — COMMENTED** [review]
Lgtm!

**Review by SreeeS — APPROVED** [review]

**Pull request merged**
