### PR TITLE
[WIP] Use dep

### PR DESCRIPTION
**Pull request by petderek**
### Summary
Use [dep](https://github.com/golang/dep) instead of [godep](https://github.com/tools/godep).

### Implementation details

See `agent/Gopkg.toml` and `agent/Gopkg.lock`. 

### Testing
- [x] Builds on Linux (`make release`)
- [ ] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [ ] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [ ] Integration tests on Linux (`make run-integ-tests`) pass
- [ ] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [ ] Functional tests on Linux (`make run-functional-tests`) pass
- [ ] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

### Licensing

This contribution is under the terms of the Apache 2.0 License: yes

### CODE REVIEW

**Comment by samuelkarp** [comment]
> agent\vendor\github.com\docker\docker\pkg\term\term_windows.go:12:2: case-insensitive import collision: "github.com/aws/amazon-ecs-agent/agent/vendor/github.com/Sirupsen/logrus" and "github.com/aws/amazon-ecs-agent/agent/vendor/github.com/sirupsen/logrus"

It looks like Gopkg.lock contains both:

```toml
[[projects]]
  name = "github.com/Sirupsen/logrus"
  packages = ["."]
  revision = "f006c2ac4710855cf0f916dd6b77acf6b048dc6e"
  version = "v1.0.3"

# ...

[[projects]]
  name = "github.com/sirupsen/logrus"
  packages = ["."]
  revision = "f006c2ac4710855cf0f916dd6b77acf6b048dc6e"
  version = "v1.0.3"
```

A number of projects have had issues with this, see https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276 for context.

**Comment by samuelkarp** [comment]
More errors in AppVeyor:

> agent\vendor\github.com\docker\docker\api\types\client.go:8:2: cannot find package "github.com/docker/docker/api/types/container"

**Comment by samuelkarp** [comment]
I think (at least some of) the issues you were having converting from Godep should be resolved with [v0.3.1](https://github.com/golang/dep/releases/tag/v0.3.1) (see https://github.com/golang/dep/issues/924 for context).

**Comment by petderek** [comment]
closing in favor of #1009

**Pull request closed without merging**
