### PR TITLE
Fix broken default make target 'docker'

### PR DESCRIPTION
**Pull request by fenxiong**
### Summary

This was missed in https://github.com/aws/amazon-ecs-agent/pull/1985. See that pr for details.

### Testing

"make" passes with the fix.

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yumex93** [comment]
We actually have other dockerfiles also being updated to golang:1.12, do you wanna also double check those?

**Comment by fenxiong** [comment]
> We actually have other dockerfiles also being updated to golang:1.12, do you wanna also double check those?

I checked "make test-registry" and it's working fine.

**Comment by yunhee-l** [comment]
FYI TestContainerHealthMetricsWithStartPeriod timed out for windows ftest, re-triggered it.

**Comment by yunhee-l** [comment]
TestContainerHealthMetricsWithStartPeriod test failure: https://github.com/aws/amazon-ecs-agent/issues/1991

**Pull request merged**
