### PR TITLE
ecs_client/model, functional_tests: updated model, functional tests for adding and dropping Linux capabilities

### PR DESCRIPTION
**Pull request by sharanyad**
### Summary
Model changes to Container Definition for enabling capadd and capdrop for Linux containers. 

Functional tests

TODO:
- Documentation for the new structures
- Change required agent version for cap-add, cap-drop tests

### Implementation details
- Model changes in ContainerDefinition of the form:
```javascript
linuxParameters: {
    capabilities: {
        add: [""],
        drop: [""]
    }
}
```
- Functional Tests that verify if the specified capability has been added to and dropped from the task's container

### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [x] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes: yes

### Licensing

This contribution is under the terms of the Apache 2.0 License:  yes

### CODE REVIEW

**Comment by sharanyad** [comment]
@aaithal Not very particularly. Just had it that way since they(cap-add/cap-drop) are separate flags in docker run. Would you prefer it the other way?

**Comment by aaithal** [comment]
If we could model it in the same task def, that would be better as it'd reduce the boot strapping overhead for a new test.

**Comment by samuelkarp** [comment]
Code looks good.  Can you rebase and resolve conflicts?

**Comment by samuelkarp** [comment]
@sharanyad I think we can merge this whenever you're ready.

**Comment by sharanyad** [comment]
Updated the API and documentation for the new structures. Let's merge once the builds pass.

**Comment by sharanyad** [comment]
Updated API and Docs to the latest version. 
Removed `LaunchType` from API as per @aaithal 's comment.

**Comment by sharanyad** [comment]
All builds and tests pass
@samuelkarp @aaithal Could you please have a quick look once?

**Pull request merged**
