### PR TITLE
V1.26.0 stage

### PR DESCRIPTION
**Pull request by petderek**
### Summary

Updating Agent to 1.26.0. Changelog:

* Feature - Startup order can now be explicitly set via DependsOn field in the Task Definition [#1904](https://github.com/aws/amazon-ecs-agent/pull/1904)
* Feature - Containers in a task can now have individual start and stop timeouts [#1904](https://github.com/aws/amazon-ecs-agent/pull/1904)
* Feature - AWS App Mesh CNI plugin support [#1898](https://github.com/aws/amazon-ecs-agent/pull/1898)
* Enhancement - Containers with links and volumes defined will now shutdown in the correct order [#1904](https://github.com/aws/amazon-ecs-agent/pull/1904)
* Bug - Image cleanup errors fixed [#1897](https://github.com/aws/amazon-ecs-agent/pull/1897)

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yumex93** [comment]
The cni plugin name is aws-appmesh. I think we should use either AWS App Mesh or aws-appmesh.

**Comment by yumex93** [comment]
TestStateManager failed in linux unit test

**Comment by petderek** [comment]
Unit tests are still flaking even after updating to faster drives. Unit tests are still passing in travis.

**Comment by ubhattacharjya** [comment]
Windows Flaky Functional Tests 'TestOOMContainer', 'TestV3TaskEndpointTags', ''TestV3TaskEndpointDefaultNetworkMode' passed in local ec2 windows instance when I tried reproducing it
Reference: https://github.com/aws/amazon-ecs-agent/issues/1869

**Comment by ubhattacharjya** [comment]
Arm function tests failed because of flaky test 'TestTelemetry' and I have tested in an arm instance with latest code.

Reference: https://github.com/aws/amazon-ecs-agent/issues/1903

**Comment by petderek** [comment]
Windows test was fixed in #1919

**Pull request merged**
