### PR TITLE
init-agent integration al1

### PR DESCRIPTION
**Pull request by lydiafilipe**
### Summary
This pr is an initial commit to integrate ecs init *as-is* and ecs agent for our AL1 versions. This follows a similar approach to https://github.com/aws/amazon-ecs-agent/pull/3141, which was done for our current latest versions.

### Implementation details
Created clones of both the init and agent packages.

Removed/changed some of the files that would conflict in the init package and committed the changes:
```
git clone --branch v1.51.0-1 https://github.com/aws/amazon-ecs-init.git
git checkout -b initAgentPreMerge
git remote rm origin
git rm .github/ISSUE_TEMPLATE.md
git rm .github/PULL_REQUEST_TEMPLATE.md
git rm .gitignore
git mv Makefile init_Makefile
git mv CHANGELOG.md INIT_CHANGELOG.md
git rm NOTICE
git mv README.md INIT_README.md
git rm THIRD-PARTY
git rm scripts/analyze-cover-profile
git rm CODE_OF_CONDUCT.md
git rm CONTRIBUTING.md
git commit -a -m "file changes for merge"
git gc --aggressive 
```

Created initAgentIntegrationAL1 branch in upstream from the 1.51.0 tag. Then ran the following in the agent package to merge init:
```
git clone --branch v1.51.0 https://github.com/aws/amazon-ecs-agent.git
git checkout -b initAgentIntegrationAL1
git remote add init ~/go/src/repoclones/amazon-ecs-init
git fetch init --tags
git pull init initAgentPreMerge --allow-unrelated-histories
```

Pushed to this branch.

The static checks currently fail for the agent version tagged at 1.51.0, as evidenced by [this](https://github.com/aws/amazon-ecs-agent/pull/3151) pr, so for this pr we also removed the static check from the worflow.

### Description for the changelog
Base changes to integrate ECS Init into ECS Agent for AL1

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by YashdalfTheGray** [comment]
This is just to merge into 1.51 so that all the fix branches can be rebased?

That being said, is there something that I should be looking for in this PR? Looking at the diff kinda breaks Chrome for a while 😂

**Comment by lydiafilipe** [comment]
> This is just to merge into 1.51 so that all the fix branches can be rebased?
Yeah this merges init 1.51.0-1 into agent 1.51 so that we have the unified/simplified build for the legacy version of agent and can apply required fixes as needed

> That being said, is there something that I should be looking for in this PR? Looking at the diff kinda breaks Chrome for a while 😂
Besides the files I mentioned in the description, nothing has been changed from the ecs-init repo, so the diff isn't particularly meaningful, it's just all of the init files

**Review by fierlion — APPROVED** [review]
Changes look good.
(As we discussed, we'll want to add the static checks back in the next commit; we'll update the branch protection rules once the static check is back in place.)

**Comment by YashdalfTheGray** [comment]
> Besides the files I mentioned in the description, nothing has been changed from the ecs-init repo, so the diff isn't particularly meaningful, it's just all of the init files

This is what I figured, sounds good!

**Review by YashdalfTheGray — APPROVED** [review]

**Pull request merged**
