### PR TITLE
Bump version to 1.5.0

### PR DESCRIPTION
**Pull request by samuelkarp**
* Feature - Add support for additional Docker features.
* Feature - Detect and register capabilities.
* Feature - Add -license flag and /license handler.
* Enhancement - Properly handle throttling.
* Enhancement - Make it harder to accidentally expose sensitive data.
* Enhancement - Increased reliability in functional tests.
* Bug - Fixed potential divide-by-zero error with metrics.

r? @euank @aaithal

### CODE REVIEW

**Comment by euank** [comment]
:+1:

**Comment by CpuID** [comment]
@samuelkarp @euank do you mind if I ask when some of the new 1.5.0 functionality will be exposed via the ECS APIs, specifically the extra attributes in Task Definitions that this version expands on (privileged mode, etc)? Not holding you to a specific date, just a rough guess is fine.

Before re:Invent? During re:Invent? After re:Invent? :)

**Comment by euank** [comment]
The ECS APIs support this now and we're in the process of adding these fields to the ECS console.
We'll also roll out an update for the cli and SDKs in the near future, though if you wanted to nab the [model file](https://github.com/aws/amazon-ecs-agent/tree/v1.5.0/agent/ecs_client/model/api) from this codebase, it'd work now.

Best,
Euan

**Comment by CpuID** [comment]
@euank thanks :) awesome.

**Comment by joostdevries** [comment]
Is the list of `attributes` used during registration customizable using `ecs.config`?

**Comment by euank** [comment]
They are not currently customizable, @joostdevries.
Thanks for the information on your use case.

**Pull request merged**
