### PR TITLE
merge master to dev "update to 1.25.3"

### PR DESCRIPTION
**Pull request by suneyz**
### Testing

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by petderek** [comment]
@aaithal, this isn't a release PR. We didn't merge the changelog entry into both master and dev last time.

**Comment by aaithal** [comment]
Sorry, misread it, my bad. It's probably even more worrying that bringing `dev` up to date with `master` results in test failures

> @aaithal, this isn't a release PR. We didn't merge the changelog entry into both master and dev last time.

Sorry, misread it, my bad. It's probably even more worrying that bringing `dev` up to date with `master` results in test failures.

**Comment by petderek** [comment]
Part of it was I temporarily had our CI broken on windows integ / functional tests. I'm re-running those.

**Comment by suneyz** [comment]
tests passed. thanks derek!

**Pull request merged**
