### PR TITLE
Add ecs specific labels

### PR DESCRIPTION
**Pull request by ejholmes**
Re-opening https://github.com/aws/amazon-ecs-agent/pull/88#issuecomment-104445099 against the dev branch.

Closes https://github.com/aws/amazon-ecs-agent/issues/82

### CODE REVIEW

**Comment by euank** [comment]
:+1:, LGTM

**Comment by samuelkarp** [comment]
:+1:

**Comment by ejholmes** [comment]
Thanks guys!

**Comment by samuelkarp** [comment]
Thanks for the contribution!

**Pull request merged**
