### PR TITLE
Feature/debugging ecs agent volume runc integration

### PR DESCRIPTION
**Pull request by KensoDev**
While debugging this issue https://github.com/aws/amazon-ecs-agent/issues/951 and diving into the code quite a bit, Refactored a bit of code to return errors and format errors in a more readable way.

Main changes are that functions returns error if something unexpected happen vs true/false and also formatting strings vs concat which makes it easier to read.

### CODE REVIEW

**Comment by KensoDev** [comment]
Will fix tests. Sorry for the confusion

**Comment by KensoDev** [comment]
Tests fixed

**Comment by jhaynes** [comment]
@KensoDev Thanks for submitting this PR and for the time you spent debugging. We're reviewing this internally.

**Comment by KensoDev** [comment]
Hi @aaithal, I will definitely make those changes.

**Comment by aaithal** [comment]
Thanks! Also, can you please confirm this contribution is under the terms of the Apache 2.0 license?

**Comment by KensoDev** [comment]
@aaithal TBH, I have no idea what this means.

**Comment by aaithal** [comment]
@KensoDev ECS Agent is published under the Apache 2.0 License. We want you to confirm that your contribution is under the same license as ECS Agent. 

Thanks,
Anirudh

**Comment by samuelkarp** [comment]
@KensoDev We can't merge your change unless you agree that your contribution is under the terms of the Apache 2.0 license.  I'm going to close this for now, but we'd be happy to take the contribution if you can confirm your agreement.

**Pull request closed without merging**
