### PR TITLE
Run windows unit tests on travis

### PR DESCRIPTION
**Pull request by petderek**
### Summary
Makes it so that we can run Windows unit tests on travis. Also removes appveyor config.

### Implementation details
Travis will now run:
- windows unit tests using the windows platform
- windows build on linux platform (as part of the xplatform build target)
- linux build on linux platform

### Testing
I tested this on my personal repo, so hopefully the travis run will succeed here.

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yunhee-l** [comment]
appveyor has failed, please check that before pushing.

**Comment by petderek** [comment]
It failed because I deleted the yml file. We can stop using it now that Travis runs the windows unit tests.

**Comment by yunhee-l** [comment]
ok we should update our checks to remove it then.

**Comment by petderek** [comment]
Yep. I wanted to get sign off here before I removed it.

**Comment by adnxn** [comment]
lol @ does this require the appveyor thing to pass?

**Comment by petderek** [comment]
I'm going to go ahead and merge this since it isn't impacted by the mongodb test image.

**Pull request merged**
