### PR TITLE
ACK duplicate StageUpdateMessages

### PR DESCRIPTION
**Pull request by samuelkarp**
ACK duplicate messages instead of ignoring.  Network instability or other errors can prevent the first ACK from being received, causing additional StageUpdateMessages to be sent.

@dangrd @euank

### CODE REVIEW

**Comment by euank** [comment]
LGTM. 
Might want to add a comment explaining that you can't be in 'updateDownloading' here because of the lock or even make an explicit, but presently redundant, condition of it just to be cautious.

**Comment by samuelkarp** [comment]
@euank Thinking about it more, it also seems like I might benefit from adding `error` into the `updater` struct such that I can correctly (n)ack based on the previous `download` result.  Thoughts?

**Comment by euank** [comment]
You'd need to keep track of an `error<->updateIdentifer` associations outside the `updater` struct because on `nack` the `updater` should always to back to state `none` with a blank identifier.

I'd also be concerned about such a mapping if there is no expiration associated with the cache of recent update failures (throw in successes too if you want to do it).
If there's no eviction, you end up with a single failure leaving an error which results in all other attempts at updating to the same target failing.

Part of the problem might be the broad scope of the lock. Moving it to only encompass portions where the state is actually changed would let `downloading` be observed could lead to better behavior, especially with regard to repeated requests, but still would not add meaning to saving errors (just a better way to distinguish `downloading->discard` vs `downloaded->ack` for duplicates).

**Comment by samuelkarp** [comment]
@euank I think this is actually safe as-is, since a `nack` will clear the `updater` state, but a successful download will leave it there.  In the case of a different update request, the existing code already handles this.  I've added a clarifying comment and additional unit test.

**Comment by aaithal** [comment]
:shipit:

**Pull request merged**
