### PR TITLE
Update libcni to the latest version

### PR DESCRIPTION
**Pull request by richardpen**
### Summary

Update the containernetworking/cni to the latest version that take a context in the API.

### Implementation details

Update the dependency package and the API in ecscni package.

### Testing

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yunhee-l** [comment]
TestV3TaskEndpointAWSVPCNetworkMode failed for both arm and linux functional tests. I'll retry functional tests in case these are being flakey, since it used to be, although it's been fixed for a while. But I'm wondering if there's any real impact of upgrading cni lib.

**Comment by richardpen** [comment]
@yunhee-l Thanks, looks like these failure are caused by the cni configuration version. I'm working on the fix, will update.

**Comment by yunhee-l** [comment]
can you rebase from dev again please?

**Comment by richardpen** [comment]
@yunhee-l I have just rebased on top of dev, can you take another look?

**Comment by yumex93** [comment]
Why it is upgraded to v0.7.0 not v0.8.0? v0.8.0 should be the latest version.

**Pull request merged**
